### ISSUE TITLE
Having problem running finishm 0.0.7

### ISSUE THREAD

**Issue by fauziharoon** [wwood/finishm#37]
While running finishm roundup - 

[8906.869103] Threading through reads 99000000 / 137790180
[8940.4240
        from /usr/local/lib/ruby/gems/2.1.0/gems/bio-velvet-0.6.0/lib/bio-velvet/runner.rb:25:in `velvet'
        from /usr/local/lib/ruby/gems/2.1.0/gems/finishm-0.0.7/lib/assembly/graph_generator.rb:100:in `block in generate_graph'
        from /usr/local/lib/ruby/2.1.0/tempfile.rb:324:in `open'
        from /usr/local/lib/ruby/gems/2.1.0/gems/finishm-0.0.7/lib/assembly/graph_generator.rb:72:in `generate_graph'
        from /usr/local/lib/ruby/gems/2.1.0/gems/finishm-0.0.7/lib/finishm/roundup.rb:121:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/finishm-0.0.7/bin/finishm:138:in `<top (required)>'
        from /usr/local/bin/finishm:23:in `load'
        from /usr/local/bin/finishm:23:in `<main>'

**Comment by wwood** [comment]
hey, hard to tell from that. Can you report the full log output either here or just email me? I have the suspicion it ran out of memory but it is hard to tell.

**Comment by fauziharoon** [comment]
Emailed. Thanks!
