### ISSUE TITLE
roundup 'velvetg' error

### ISSUE THREAD

**Issue by epulo5** [wwood/finishm#42]
I've recently installed finishm and am getting the following error when running roundup. Any help would be appreciated! I have Ruby 2.3.
```
>finishm roundup --genomes geno                                             mes/Final_Genomes/Final/JHnorm_finalGeneious112.fasta --interleaved-fastq-gz Jge                                             nome_working/unmerged_JH.ecc.fq.gz --fastq-gz Jgenome_working/merged_JH.ecc.fq.g                                             z --output-directory Jgenome_working/finishm/

 WARN finishm 22/05 12:30:35: Found unexpected characters in the sequence scaf60                                             _13_21_meta2_142 e.g. Y. Replacing them with Ns
 WARN finishm 22/05 12:30:35: Found unexpected characters in the sequence scaf89                                             _230_177_meta41rev e.g. M. Replacing them with Ns
 WARN finishm 22/05 12:30:35: Found unexpected characters in the sequence scaffo                                             ld_scaf55_scaf49 e.g. Y. Replacing them with Ns
 INFO finishm 22/05 12:30:35: Detected 112 scaffolds, containing 122 different c                                             ontigs
 WARN finishm 22/05 12:30:35: Removed 4 contigs from within scaffolds as they we                                             re too short
 INFO bio-velvet 22/05 12:30:35: Running velveth: /home/roli/Software/finishm/li                                             b/assembly/../../ext/src/velveth
 INFO finishm 22/05 12:30:35: Assembling sampled reads with velvet
 INFO bio-velvet 22/05 12:30:35: Running velveth: /home/roli/Software/finishm/li                                             b/assembly/../../ext/src/velveth /tmp/runner_1495470635_331 51  -fasta -short /t                                             mp/probes.fa20170522-126107-wy6nhm -fastq.gz -short Jgenome_working/merged_JH.ec                                             c.fq.gz -fastq.gz -shortPaired Jgenome_working/unmerged_JH.ecc.fq.gz -create_bin                                             ary

 INFO bio-velvet 22/05 12:46:21: Running velvetg: /home/roli/Software/finishm/li                                             b/assembly/../../ext/src/velvetg /tmp/runner_1495470635_331 -read_trkg yes -cov_                                             cutoff 3.5 -tour_bus no -read_to_node_binary yes
/var/lib/gems/2.3.0/gems/bio-velvet-0.6.0/lib/bio-velvet/runner.rb:75:in `velvet                                             g': Error running velvetg:  (Bio::Velvet::VelvetRunnerException)
        from /var/lib/gems/2.3.0/gems/bio-velvet-0.6.0/lib/bio-velvet/runner.rb:                                             25:in `velvet'
        from /home/roli/Software/finishm/lib/assembly/graph_generator.rb:100:in                                              `block in generate_graph'
        from /usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
        from /home/roli/Software/finishm/lib/assembly/graph_generator.rb:72:in `                                             generate_graph'
        from /home/roli/Software/finishm/lib/finishm/roundup.rb:121:in `run'
        from /home/roli/Software/finishm/bin/finishm:138:in `<main>'
```

**Comment by wwood** [comment]
Hi, thanks for your interest in FinishM. I'm not quite sure as there's no useful error message printed.

Could you try to debug by setting the `--velvet-directory` flag? Then the velvet files will be kept and the `velvetg` command can be run directly and error(s) printed.

Thanks

**Comment by epulo5** [comment]
Thanks for help. I set the --velvet-directory flag and noticed that I forgot to install clustalo. Er, sorry.  

However, I've run into a new problem. Our server is partitioned so that the root (and thus /tmp) have limited space to grow (i.e. not designed to hold the output from assemblies). Is it possible for a user to specify where the temporary files are created when using finishM?

**Comment by wwood** [comment]
Do you mean setting the temprorary directory with `--velvet-directory`
outside of `/tmp`? From memory most of the big files are put into that
temporary directory.

If you mean otherwise I imagine you can set the `TMDIR` environment
variable which IIRC Ruby respects.
